### ISSUE TITLE
Could you provide an example in README how to add ca certificate?

### ISSUE THREAD

**Issue by fr6nco** [salt-formulas/salt-formula-linux#120]
I could not figure out how to use the contents_pillar thing in the certificates.sls file

Could you write an example to the readme with a short description how to use it? 

Thank you

**Comment by fpytloun** [comment]
Done :-)

**Comment by fr6nco** [comment]
Meanwhile sort of figured out from the sources, but anyways, thank you. I really appreciate it :)
