### ISSUE TITLE
linux.system.atop failed

### ISSUE THREAD

**Issue by mnederlof** [salt-formulas/salt-formula-linux#140]
I guess there is typo, because the file linux/system/atop.systemd exists, but linux/system/atop.service does not

Upon deployment i get these errors from salt:
----------
          ID: atop_systemd_file
    Function: file.managed
        Name: /etc/systemd/system/atop.service
      Result: False
     Comment: Source file salt://linux/files/atop.service not found
     Started: 16:26:41.545989
    Duration: 3.423 ms
     Changes:
----------
          ID: atop_service
    Function: service.running
        Name: atop
      Result: False
     Comment: One or more requisite failed: linux.system.atop.atop_systemd_file
     Changes:

**Comment by fpytloun** [comment]
Thank you for reporting this
