### ISSUE TITLE
linux_kernel_net.nf_conntrack_max failing

### ISSUE THREAD

**Issue by tomkukral** [salt-formulas/salt-formula-linux#55]
This action is failing on some deployments (virtualized), module then returns non-zero.

```
          ID: linux_kernel_net.nf_conntrack_max
    Function: sysctl.present
        Name: net.nf_conntrack_max
      Result: False
     Comment: Failed to set net.nf_conntrack_max to 1048576: sysctl net.nf_conntrack_max does not exist
     Started: 10:29:50.407214
    Duration: 21.099 ms
     Changes: 
```

**Comment by fpytloun** [comment]
Then it should not be defined in metadata.
Where is it coming from?

It's possibly to add conditional to don't set options that cannot be set but I would prefer to fix metadata model instead.

**Comment by tomkukral** [comment]
It was defined in `classes.system.linux.system.single` 

Closing issue since problem is not related to this formula.
