### ISSUE TITLE
unattended-upgrades to install security upgrades automatically on Debian-like systems

### ISSUE THREAD

**Issue by bbinet** [salt-formulas/salt-formula-linux#60]
It would be great if salt-formula-linux could allow to install and configure unattended-upgrades to enhance security on Debian-like systems.
See: https://wiki.debian.org/UnattendedUpgrades

If you agree with the feature, I can provide a pull-request, but I'd like some guidance on where to put the unattended-upgrades stuff.

**Comment by fpytloun** [comment]
Hello, I think that's good idea :-)
I would introduce state that will take care of automated updates and that will be universal across distributions, eg. on Debian it will use unattended updates, on RHEL-based there are autoupdates as well (https://fedoraproject.org/wiki/AutoUpdates).

I would name it `linux.system.autoupdates` (as it's more obvious naming than unattended updates) and design metadata structure like:

**Comment by bbinet** [comment]
Thanks for your answer @fpytloun
I will try to prepare a pull request with support for the metadata you've described, but I won't be able to support other distributions than Debian-like systems (because we're running exclusively Debian systems here).

**Comment by fpytloun** [comment]
That's ok, just add Debian support and let the doors open for some RHEL/Fedora user to finish it for their distro of choice :-)
Submit pull req. when you're done, or feel free to join our Gitter/IRC and ask if you need support.

**Comment by bbinet** [comment]
That's perfect, thanks!
